// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using postest.Models;

namespace postest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("postest.Models.Catigories", b =>
                {
                    b.Property<int>("CAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CAT_ID");

                    b.ToTable("Catigories");
                });

            modelBuilder.Entity("postest.Models.Items", b =>
                {
                    b.Property<int>("ITEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CAT_ID")
                        .HasColumnType("int");

                    b.Property<int?>("CatigoriesCAT_ID")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ITEM_ID");

                    b.HasIndex("CatigoriesCAT_ID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("postest.Models.Items", b =>
                {
                    b.HasOne("postest.Models.Catigories", "Catigories")
                        .WithMany("Items")
                        .HasForeignKey("CatigoriesCAT_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
